// React framework for production
// next js provides additional features like routing, optimzed rendering, data fetching, bundling, server side rendering, static site generation, api routes, image optimization, css and sass support, typescript support, and more
// next js is a react framework for production ready applications

//featues
//1) file based routing  - pages folder - eliminates the need for react router packege
//2) Api routes - api folder - for serverless functions
// 3) server side rendering - faster initial load time
//4) Data fetching - getServerSideProps, getStaticProps, getStaticPaths
//5) Image optimization - next/image component
//6) Css and Sass support - built in support
// 7) dev and prod build - next build, next start
// 8) better SEO support

// we can add metadata  includes title, keywords, description, and more to the layout.js file so this metadata is available to all pages
// search engine crawlers can use this metadata to index the page and display it in search results

// client vs server side rendering
//1)client side rendering -
//-react app is rendered in the browser
//-initial load time is slower
//-page content is generated by the browser
//-better for dynamic content
// -better for user interactions
// -worse for SEO
// -worse for performance
// use react router for client side rendering
// user react hooks for data fetching

// 2)server side rendering
// -react app is rendered on the server
// -initial load time is faster
// -page content is generated by the server
// -better for SEO
// -better for performance
// -worse for user interactions
// next js provides server side rendering by default
// next js provides file based routing
// direct access to the ORM()

// any server component can directly access the ORM(database) and fetch data

//use client use react functinality in next componenet

//API Router
// next js provides api routes for serverless functions
// api routes are stored in the api folder
// api routes are serverless functions that run on the server
// api routes can be used to fetch data from the database, send emails, and more
// api routes are used for server side rendering
// api routes are used for client side rendering
//

//Next Auth
// Next auth is used

//server action
// server action are function that run on server
//ser

//protecting routes
// we can protect routes by using the session object
// we can use the session object to check if the user is authenticated
// we can use the session object to check if the user is an admin

// next-auth middleware
// next-auth provides middleware to protect routes
// next-auth middleware is to create a protected route to check if the user is authenticated
